version: "3"

services:
  nginx:
    build:
      context: ./.docker/nginx
    container_name: nginx
    depends_on:
      - php
    ports:
      - '8666:80'
    volumes:
      - ./src/:/app
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build:
      context: ./.docker/php
    container_name: php
    volumes:
      - ./src/:/app
    expose:
      - 9000

  #mysql: